<?php
// config.php - Database and application configuration
// AUTO-GENERATED BY setup.php - DO NOT EDIT MANUALLY

return [
    'db_host' => 'localhost',
    'db_name' => 'sms_db_test',
    'db_user' => 'root',
    'db_pass' => 'password',
    'base_url' => 'http://localhost:8008/public'
];